Traceback (most recent call last):
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/pudb/__init__.py", line 153, in runscript
    dbg._runscript(mainpyfile)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/pudb/debugger.py", line 468, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "out3.py", line 150, in <module>
    dream_img = run_deep_dream_simple(thisInput,100, 0.005)
  File "out3.py", line 139, in run_deep_dream_simple
    loss, thisInput = deepdream(thisInput, run_steps, tf.constant(step_size))
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 3211, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/csprh/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NameError: in converted code:

    out3.py:106 __call__  *
        loss = calc_loss(thisInput, self.model)
    out3.py:75 calc_loss  *
        print ("Layer_activtations{}  a".format(np.shape(this_class)))

    NameError: name 'this_class' is not defined

